data:
  annotations_path: data/annotated/260219_merge_cleaned.csv
  iob_dir: data/IOB
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  random_seed: 42
  augment: true
  augment_n_copies: 3
  biotools_path: biotoolspub/biotoolspub_with_topic.tsv

model:
  pretrained: bioformers/bioformer-16L
  dropout: 0.2
  num_labels: 3

training:
  epochs: 50
  learning_rate: 1.0e-5
  batch_size: 4
  gradient_accumulation_steps: 2
  warmup_ratio: 0.1
  weight_decay: 0.01
  bf16: true
  output_dir: models
  save_strategy: epoch
  evaluation_strategy: epoch
  load_best_model_at_end: true
  metric_for_best_model: f1
  seed: 42
  logging_dir: logs
  logging_steps: 250
  early_stopping_patience: 5

inference:
  checkpoint_path: models/checkpoint-14050
  input_path: data/to_predict/250805_mentions_with_topics.csv
  output_path: data/predicted/results.csv
  batch_size: 16
  max_length: 512
