data:
  annotations_path: data/annotated/merged_annotated.csv
  iob_dir: data/IOB_no_aug
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  random_seed: 42
  augment: false
  include_negatives: false
  biotools_path: biotoolspub/biotoolspub_with_topic.tsv

model:
  pretrained: bioformers/bioformer-16L
  dropout: 0.2
  num_labels: 3

training:
  epochs: 4
  max_steps: -1
  learning_rate: 1.0e-5
  batch_size: 4
  gradient_accumulation_steps: 2
  warmup_ratio: 0.1
  weight_decay: 0.01
  bf16: true
  output_dir: models/no_aug
  save_strategy: epoch
  save_steps: 500
  evaluation_strategy: epoch
  eval_steps: 500
  load_best_model_at_end: true
  metric_for_best_model: f1
  seed: 42
  logging_dir: logs/no_aug
  logging_steps: 250
  early_stopping_patience: 5
